### ISSUE TITLE
我不是搞安全的，也不是运维，但是我发现……

### ISSUE THREAD

**Issue by crzidea** [LeadroyaL/pdd_3years#3]
根据作者提供的 access.log，查了一下访问 IP，以下是访问量前 5 的 IP，其中前三占比 64%，访问次数最多的一个是 101.89.34.219，占比 46%，其他的都不重要。
**然后我查了一下这个 IP 的归属地，是上海电信，应该是殡多多公司固定的出口 IP 无疑了。**
~~希望有能力且有良知的打工人、大佬、友商、竞对们能团结起来给这个 IP 一点颜色看看。做空殡多多，从这一件小事做起！~~
看了一下这个 IP 开放了 80 和 443 端口，自签证书上面的常用名称为 *.cdn.myqcloud.com，应该还会被作为 CDN 源站使用。连接后不发数据可保持长连接时间为 1 分钟。

IP | 访问次数 | 占比
-- | -- | --
101.89.34.219 | 35993 | 46%
59.36.119.251 | 7999 | 10%
123.151.144.18 | 6002 | 8%
不重要 | 1787 | 2%
不重要 | 1416 | 2%

**Comment by evilAdan0s** [comment]
从五点到十一点，这个IP出现了三万多次，每次都换UA头，有可能是cc

**Comment by crzidea** [comment]
> 从五点到十一点，这个IP出现了三万多次，每次都换UA头，有可能是cc

办公网出口 IP 访问的时候换 UA 很正常啊，因为员工的设备确实都不一样~

**Comment by zjlywjh001** [comment]
看了一下现象，目测是CC。

**Comment by prs1022** [comment]
从删除用户手机照片的尿性，殡多多会来github删issue吗？mark留名以后回来看

**Comment by Yangff** [comment]
这是他的CDN的ip吧……

**Comment by paradiseduo** [comment]
```
上海寻死信息技术有限公司给你点赞
```

**Comment by 1976222027** [comment]
网络大事件

**Comment by AzDj** [comment]
*.cdn.myqcloud.com是腾讯云的cdn证书= =

**Comment by LeadroyaL** [comment]
机器access.log是来自 CDN的回源请求，估计是服务器扛不住挂了，个人认为楼主分析的不对，close 了。
